DSWI-TiendaJulio/Controllers/EcommerceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using DSWI_TiendaJulio.Models;

namespace DSWI_TiendaJulio.Controllers
{
    public class ECommerceController : Controller
    {
        string cadena = ConfigurationManager.ConnectionStrings["cn"].ConnectionString;

        //TIENDA

        IEnumerable<Producto> productos()
        {
            List<Producto> temporal = new List<Producto>();
            SqlConnection cn = new SqlConnection(cadena);
            SqlCommand cmd = new SqlCommand(
            "SELECT COD_PRO, NOM_PRO, PRECIO_VENTA, STOCK FROM PRODUCTO", cn);
            cn.Open();
            SqlDataReader dr = cmd.ExecuteReader();
            while (dr.Read())
            {
                Producto reg = new Producto();
                reg.COD_PRO = dr.GetString(0);
                reg.NOM_PRO = dr.GetString(1);
                reg.PRECIO_VENTA = dr.GetDecimal(2);
                reg.STOCK = dr.GetInt32(3);
                temporal.Add(reg);
            }
            dr.Close(); cn.Close();
            return temporal;
        }

        IEnumerable<Cliente> clientes()
        {
            List<Cliente> temporal = new List<Cliente>();
            SqlConnection cn = new SqlConnection(cadena);
            SqlCommand cmd = new SqlCommand(
            "SELECT * FROM CLIENTE", cn);
            cn.Open();
            SqlDataReader dr = cmd.ExecuteReader();
            while (dr.Read())
            {
                Cliente reg = new Cliente();
                reg.dni = dr.GetString(0);
                reg.nombre = dr.GetString(1);
                reg.telefono = dr.GetString(2);
                reg.direccion = dr.GetString(3);
                reg.COD_DIS = dr.GetString(4);
                reg.idusuario = dr.GetString(5);
                temporal.Add(reg);
            }
            dr.Close(); cn.Close();
            return temporal;
        }

        IEnumerable<Producto> filtro(string nombre = null)
        {
            List<Producto> temporal = new List<Producto>();
            SqlConnection cn = new SqlConnection(cadena);
            if (nombre == null)
            {
                nombre = " ";
                SqlCommand cmd = new SqlCommand("SP_FILTRO_PRODUCTO", cn);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@nombre", nombre);
                cn.Open();
                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    Producto reg = new Producto();
                    reg.COD_PRO = dr.GetString(0);
                    reg.NOM_PRO = dr.GetString(1);
                    reg.PRECIO_VENTA = dr.GetDecimal(2);
                    reg.STOCK = dr.GetInt32(3);
                    temporal.Add(reg);
                }
                dr.Close(); cn.Close();
                return temporal;
            }
            else
            {
                SqlCommand cmd = new SqlCommand("SP_FILTRO_PRODUCTO", cn);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@nombre", nombre);
                cn.Open();
                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    Producto reg = new Producto();
                    reg.COD_PRO = dr.GetString(0);
                    reg.NOM_PRO = dr.GetString(1);
                    reg.PRECIO_VENTA = dr.GetDecimal(2);
                    reg.STOCK = dr.GetInt32(3);
                    temporal.Add(reg);
                }
                dr.Close(); cn.Close();
                return temporal;
            }
        }

        Producto Buscar(string id = null)
        {
            if (id == null)
                return new Producto();
            else
                return productos().Where(p => p.COD_PRO == id).FirstOrDefault();

        }

        public ActionResult Tienda(string nombre = null)
        {
            //primero evaluo si existe el Session["carrito"]
            //el cual permitira almacenar los productos seleccionados(1 vez)
            if (Session["carrito"] == null)
                Session["carrito"] = new List<Item>();

            //asignar a ViewBag.usuario en nombre del cliente InicioSesion()
            ViewBag.usuario = InicioSesion();

            List<Item> temporal = (List<Item>)Session["carrito"];

            ViewBag.totalcarrito = temporal.Count;

            return View(filtro(nombre));
        }

        public ActionResult Agregar(string id = null)
        {
            if (id == null) return RedirectToAction("Tienda");

            //asignar a ViewBag.usuario en nombre del cliente InicioSesion()
            ViewBag.usuario = InicioSesion();

            List<Item> temporal = (List<Item>)Session["carrito"];

            ViewBag.totalcarrito = temporal.Count;

            //si id no es null, envio los datos del producto
            return View(Buscar(id));
        }

        [HttpPost] public ActionResult Agregar(string cod, Int16 stock, int cantidad)
        {
            if (cantidad > stock)
            {
                ViewBag.mensaje = "Ingrese una cantidad menor al stock";
                return View(Buscar(cod));
            }
            // a continuacion recupero el Producto por su cod
            Producto reg = Buscar(cod);
            //instanciar Item y pasar sus datos
            Item it = new Item()
            {
                codigo = reg.COD_PRO,
                descripcion = reg.NOM_PRO,
                precio = reg.PRECIO_VENTA,
                cantidad = cantidad,
            };
            //agregar it al Session carrito, referenciar con temporal
            List<Item> temporal = (List<Item>)Session["carrito"];
            temporal.Add(it);
            //asignar a ViewBag.usuario en nombre del cliente InicioSesion()
            ViewBag.usuario = InicioSesion();

            ViewBag.mensaje = "Producto Agregado";

            ViewBag.totalcarrito = temporal.Count;

            return View(reg);
        }

        public ActionResult Canasta()
        {
            //asignar a ViewBag.usuario en nombre del cliente InicioSesion()
            ViewBag.usuario = InicioSesion();

            List<Item> temporal = (List<Item>)Session["carrito"];

            ViewBag.totalcarrito = temporal.Count;

            //visualizar el contenido del Session["carrito"], productos seleccionado
            return View((List<Item>)Session["carrito"]);
        }

        public ActionResult Delete(string id)
        {
            //eliminar el Item del Session["carrito"]
            List<Item> temporal = (List<Item>)Session["carrito"];
            //buscar
            Item reg = temporal.Find(i => i.codigo == id);
            temporal.Remove(reg);

            return RedirectToAction("Canasta");
        }

        public string InicioSesion()
        {
            if (Session["login"] == null)
                return null;
            else
                return (Session["login"] as Cliente).nombre;
        }

        Cliente Buscar(string login, string clave)
        {
            Cliente reg = null; //inicializar
            SqlConnection cn = new SqlConnection(cadena);
            SqlCommand cmd = new SqlCommand("sp_logueo", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@id", login);
            cmd.Parameters.AddWithValue("@clave", clave);
            cn.Open();
            SqlDataReader dr = cmd.ExecuteReader();
            if (dr.Read())
            {
                reg = new Cliente();
                reg.dni = dr["DNI"].ToString();
                reg.nombre = dr["NOMBRE"].ToString();
                reg.direccion = dr["DIRECCION"].ToString();
                reg.telefono = dr["TELEFONO"].ToString();
                reg.tipo_usuario = Convert.ToInt32(dr["id_tipo"].ToString());
            }
            dr.Close();
            cn.Close();

            return reg;

        }

        public ActionResult Inicio(Cliente reg)
        {
            return View(reg);
        }

        [HttpPost] public ActionResult Inicio(string login, string clave)
        {
            //ejecutar el Buscar y lo almaceno en Session["login"]
            Session["login"] = Buscar(login, clave);
            if (Session["login"] == null)
            {
                ViewBag.mensaje = "Usuario o Clave Incorrecta";
                return View();
            }
            else
            {
                int tipo_usuario = Buscar(login, clave).tipo_usuario;
                if (tipo_usuario == 4)
                {
                    return RedirectToAction("Tienda");
                }
                else
                {
                    return RedirectToAction("CrudProducto", "Ecommerce");
                }
            }
        }

        public ActionResult Registrarse()
        {
            ViewBag.distritos = new SelectList(distritos(), "COD_DIS", "NOMBRE");
            return View(new Cliente());
        }

        [HttpPost] public ActionResult Registrarse(Cliente reg, string nomusuario, string password)
        {
            SqlConnection cn = new SqlConnection(cadena);
            cn.Open();

            SqlCommand cmd = new SqlCommand("SP_CONSULTA_DNI", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@DNI", reg.dni);

            int count = (int)cmd.ExecuteScalar();

            if (count == 0)
            {
                try
                {
                    cmd = new SqlCommand("SP_REGISTRA_CLIENTE", cn);
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@DNI", reg.dni);
                    cmd.Parameters.AddWithValue("@NOMBRE", reg.nombre);

DSWI-TiendaJulio/Views/Ecommerce/Agregar.cshtml
@model DSWI_TiendaJulio.Models.Producto

@{
    ViewBag.Title = "Agregar";
    Layout = "~/Views/Shared/_LayoutCarrito.cshtml";
}

<div class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-5 col-md-push-2">
                <div id="product-main-img">
                    <div class="product-preview">
                        <img src="@Url.Content(string.Format("~/imagenes/{0}.jpg",Model.COD_PRO))" />
                    </div>
                </div>
            </div>

            <div class="col-md-2  col-md-pull-5">
             <div id="product-imgs">
                <div class="product-preview">
                    <img src="@Url.Content(string.Format("~/imagenes/{0}.jpg",Model.COD_PRO))" />
                </div>
             </div>
            </div>

            <div class="col-md-5">
                <div class="product-details">
                    <h2 class="product-name">@Html.DisplayFor(model => model.NOM_PRO)</h2>

                    <div>
                        <h3 class="product-price">S/@Html.DisplayFor(model => model.PRECIO_VENTA) soles</h3>
                    </div>
                    <div>
                        <h3 class="product-price">@Html.DisplayFor(model => model.STOCK) en stock</h3>
                    </div>

                    @using (Html.BeginForm("Agregar", "ECommerce", FormMethod.Post))
                    {
                        @Html.Hidden("cod", Model.COD_PRO)
                        @Html.Hidden("stock", Model.STOCK)
                        <div class="add-to-cart">
                            <div class="qty-label">
                                Cantidad
                                <div class="input-number">
                                    @Html.TextBox("cantidad", 1, new { @type = "number" })
                                    <span class="qty-up">+</span>
                                    <span class="qty-down">-</span>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="primary-btn order-submit"><i class="fa fa-shopping-cart"></i>ADD TO CARD</button> <span>|</span>
                        @Html.ActionLink("Retornar", "Tienda", new { nombre = TempData["nombre"] }, new { @class = "primary-btn order-submit" })
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<div style="color: red; font-size:21px">@ViewBag.mensaje</div>

DSWI-TiendaJulio/Views/Ecommerce/CrudCliente.cshtml
@model DSWI_TiendaJulio.Models.Cliente

@using DSWI_TiendaJulio.Models;


@{
    ViewBag.Title = "CrudCliente";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<hr />
<h2>Mantenimiento de Clientes</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("DNI", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dni, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dni, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("NOMBRE", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("TELÉFONO", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("DIRECCIÓN", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("DISTRITO", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("COD_DIS", (SelectList)ViewBag.distritos)
                @Html.ValidationMessageFor(model => model.COD_DIS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("USUARIO", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idusuario", (SelectList)ViewBag.usuarios)
                @Html.ValidationMessageFor(model => model.idusuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink("Limpiar", "Clienteid", new { id = "" }, new { @class = "btn btn-default" })
                <input type="submit" value="Actualizar" class="btn btn-default" />
                @Html.ActionLink("Eliminar", "Eliminarcli", new { id = Model.dni }, new { @class = "btn btn-default", onclick = "return confirm('¿Estás seguro de eliminar?');" })


            </div>
        </div>
        <hr />

        <div style="color: red; font-size:20px">
            @ViewBag.mensaje
        </div>
    </div>
}

<div class="div-lista">
    <div>
        @Html.Partial("_PartialCliente", (IEnumerable<Cliente>)ViewBag.clientes)
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DSWI-TiendaJulio/Views/Ecommerce/CrudProducto.cshtml
@model DSWI_TiendaJulio.Models.Producto
@using DSWI_TiendaJulio.Models
@{
    ViewBag.Title = "CrudProducto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    h2 {
        text-align: center;
        width: 100%;
        float: left;
    }

    .div-form {
        width: 80%;
        height: auto;
        float: left;
    }

    .div-proceso {
        width: 20%;
        height: auto;
        float: left;
    }

    .div-marco {
        width: 100%;
        height: auto;
        float: left;
    }
</style>


<h2>Mantenimiento de Productos</h2>
<div class="div-marco">

    @using (Html.BeginForm())
    {

        <div class="div-form">

            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.Label("CODIGO", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.COD_PRO, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.COD_PRO, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("NOMBRE", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.NOM_PRO, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.NOM_PRO, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("PRECIO", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.PRECIO_VENTA, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PRECIO_VENTA, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("STOCK", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.STOCK, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.STOCK, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("MARCA", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("COD_MAR", (SelectList)ViewBag.marcas)
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("CATEGORIA", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("COD_CAT", (SelectList)ViewBag.categorias)
                    </div>
                </div>

                <div style="color: red; font-size:21px">
                    @ViewBag.mensaje
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        @Html.ActionLink("Limpiar", "CrudProducto", new { id = "" }, new { @class = "btn btn-primary" })
                        <input type="submit" value="Grabar" class="btn btn-primary" />
                        @Html.ActionLink("Eliminar", "EliminaProducto", new { id = Model.COD_PRO }, new { @class = "btn btn-primary", onclick = "return confirm('¿Esta seguro de que desea eliminar?');" })
                    </div>

                </div>

            </div>

        </div>
    }

</div>
<div class="div-marco">
    @Html.Partial("_PartialProducto", (IEnumerable<Producto>)ViewBag.productos)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DSWI-TiendaJulio/Views/Ecommerce/CrudProveedor.cshtml
@model DSWI_TiendaJulio.Models.Proveedor
@using DSWI_TiendaJulio.Models

@{
    ViewBag.Title = "CrudProveedor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    h2 {
        text-align: center;
        width: 100%;
        float: left;
    }

    .div-form {
        width: 80%;
        height: auto;
        float: left;
    }

    .div-proceso {
        width: 20%;
        height: auto;
        float: left;
    }

    .div-marco {
        width: 100%;
        height: auto;
        float: left;
    }
</style>

<h2>Mantenimiento de Proveedores</h2>
<div class="div-marco">

    @using (Html.BeginForm())
    {
        <div class="div-form">

            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.Label("RUC", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.RUC, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.RUC, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("NOMBRE", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.NOMBRE, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.NOMBRE, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("CONTACTO", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.NOMBRE_CONTACTO, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.NOMBRE_CONTACTO, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("TELEFONO", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TELEFONO_CONTACTO, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TELEFONO_CONTACTO, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("DIRECCION", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DIRECCION, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DIRECCION, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("DISTRITO", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("COD_DIS", (SelectList)ViewBag.distritos)
                    </div>
                </div>

                <div style="color: red; font-size:21px">
                    @ViewBag.mensaje
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        @Html.ActionLink("Limpiar", "CrudProveedor", new { id = "" }, new { @class = "btn btn-primary" })
                        <input type="submit" value="Grabar" class="btn btn-primary" />
                        @Html.ActionLink("Eliminar", "EliminaProveedor", new { id = Model.RUC }, new { @class = "btn btn-primary", onclick = "return confirm('¿Esta seguro de que desea eliminar?');" })
                    </div>
                </div>

            </div>
        </div>
    }
</div>

<div class="div-marco">
    @Html.Partial("_PartialProveedor", (IEnumerable<Proveedor>)ViewBag.proveedores)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DSWI-TiendaJulio/Views/Ecommerce/DetalledelPedido.cshtml
@model IEnumerable<DSWI_TiendaJulio.Models.DetallePedido>

@{
    ViewBag.Title = "Detalle del Pedido";
}

<h2>Detalle del pedido seleccionado</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.cod_ven)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cod_pro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cantidad_pro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.subtotal)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.cod_ven)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cod_pro)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cantidad_pro)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.subtotal)
            </td>
        </tr>
    }

</table>

DSWI-TiendaJulio/Views/Ecommerce/Inicio.cshtml
@{
    Layout =  null;
}

<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karla:400,700&display=swap">
<link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.8.95/css/materialdesignicons.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<link rel="stylesheet" href="~/Content/login.css">

@using (Html.BeginForm())
{
   <main class="d-flex align-items-center min-vh-100 py-3 py-md-0">
       <div class="container">
          <div class="card login-card">
             <div class="row no-gutters">
                 <div class="col-md-5">
                     <img src="https://image.freepik.com/vector-gratis/fondo-tierra-dulces-colorida-estilo-hecho-mano_23-2147815166.jpg" alt="login" class="login-card-img">
                 </div>
                 <div class="col-md-7">
                    <div class="card-body">
                        <div class="brand-wrapper">
                           <img src="~/imagenes/logo.png" alt="logo" class="logo">
                        </div>
                        <p class="login-card-description">Ingresa con tu cuenta</p>
                        <form>
                            <div class="form-group">
                                <label for="usuario" class="sr-only">Email</label>
                                @Html.TextBox("login", "", new { @class = "form-control"})
                            </div>
                            <div class="form-group mb-4">
                                <label for="clave" class="sr-only">Contraseña</label>
                                @Html.TextBox("clave", "", new { @type = "password", @class= "form-control" })
                            </div>
                            <input type="submit" value="Aceptar" class="btn btn-block login-btn mb-4">
                            @Html.ActionLink("Retornar", "Tienda", new { nombre = "" }, new { @class = "btn btn-block login-btn mb-4" })
                        </form>
                        <p class="login-card-footer-text">¿No tienes una cuenta? <a href="@Url.Action("Registrarse", "Ecommerce")" class="text-reset">Registrate Aquí</a></p>
                        <nav class="login-card-footer-nav">
                           <a href="#!">Términos de uso.</a>
                           <a href="#!">Política de Privacidad</a>
                        </nav>
                     </div>
                 </div>
              </div>
          </div>
       </div>
   </main>
}

<div style="color: red; font-size:21px">
    @ViewBag.mensaje
</div>

<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

DSWI-TiendaJulio/Views/Ecommerce/ListadoPedidos.cshtml
@model IEnumerable<DSWI_TiendaJulio.Models.Pedido>

@{
    ViewBag.Title = "Pedidos";
}

<h2>PEDIDOS REALIZADOS</h2>

@using (Html.BeginForm())
{
    <div class="col-2">
        <span style="font-style: italic">Nombre de cliente</span>
        @Html.TextBox("nombre", " ", new { htmlAttributes = new { @class = "form-control" } })
        <button>Consulta</button>
    </div>}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.cod_ven)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dni)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fecha_ped)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.monto)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.cod_ven)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dni)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.fecha_ped)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.monto)
            </td>
            <td>
                @Html.ActionLink("Selecciona", "DetalledelPedido", new { id = item.cod_ven })
            </td>
        </tr>
    }

</table>

DSWI-TiendaJulio/Views/Ecommerce/Mensajes.cshtml
@{
    ViewBag.Title = "Mensajes";
    Layout = "~/Views/Shared/_LayoutCarrito.cshtml";
}

<h2 style="text-align:center">@ViewBag.mensaje</h2>

<div>
    @Html.ActionLink("Retorna", "Tienda", null, new { @class = "primary-btn order-submit" })
</div>